lib/yjit-metrics/report_templates/yjit_stats_timeline_d3_template.html.erb

Fix dom structure

---

site/_layouts/benchmark_details.erb

Without url hash return x86 if present else whatever we have

---

continuous_reporting/benchmark_and_update.rb
continuous_reporting/generate_and_upload_reports.rb
test/basic_benchmark_script_test.rb

Don't leave it up to the PATH.

Run child ruby scripts with the same ruby as the current process

---

continuous_reporting/generate_and_upload_reports.rb

The size of the single commit makes operations expensive.
It would also be nice to have a backup of the existing site in case
an update makes things go awry;
we can just pop those commits and rebuild the latest.

Append commits for built site to reports repo in the usual manner

---

lib/yjit_metrics/reports/bloggable_single_report.rb

Rather than raising when one ruby config is missing results for any
given benchmark we can remove that benchmark from the comparisons for
that platform so that report generation can proceed with the data it has.
In a recent example, several benchmarks failed on the aarch64 server.
Rather than aborting the reporting process, the aarch64 graph will simply be missing those benchmarks.
The x86 graph has all of them.

Exclude missing benchmarks from BloggableSingleReport subclasses

---

lib/yjit_metrics/reports/speed_headline_report.rb

Applicable for rebuilding some old reports.

Check for prev config before trying to find railsbench ratio

---

lib/yjit_metrics/reports/blog_yjit_stats_report.rb
lib/yjit_metrics/result_set.rb
lib/yjit_metrics/timeline_reports/yjit_speedup_timeline_report.rb

Add compile time ms to stats table and stats timeline

---

lib/yjit_metrics/timeline_reports/yjit_speedup_timeline_report.rb
site/assets/js/timeline.js
site/stats-timeline.html.erb

- **Skip compile_time_ns in stats report before timestamps that actually had it**
- **Filter out any data points that have a null value before passing to d3**

Fix yjit stats reports for any items missing data

---

basic_report.rb
timeline_report.rb

They are run as separate processes

Add RSS reports for each report script

---

setup.sh

- **Separate cpu setup by architecture**
- **Allow multiple args to perform multiple actions**
- **Add "repos" action to setup various git clones needed**
- **Use a more normal dir in case this isn't a benchmarking instance**
- **Test for presence before trying to run**
- **Comment on the package that includes perf**
- **Install pkg-config (needed to compile some native extensions)**
- **Upgrade to gcc 14**
- **Checkout the raw-benchmark-data branch that actually has data**

Add to setup script for new infrastructure

---

.github/workflows/scheduled_benchmarking.yml
.github/workflows/scheduled_reporting.yml

- **Fix syntax for reporting job**
- **Adjust schedules to bench later and report earlier**

More GA fixes

---

infrastructure/lib/yjit_benchmarking.rb

```
name     state         address           last start time   running time
yjit-benchmarking-arm   running       <ip addr>   2024-11-20 19:39:27 UTC       01:35:19
yjit-benchmarking-x86   running       <ip addr>   2024-11-20 19:39:27 UTC       01:35:19
yjit-reporting   stopped                   2024-11-20 17:46:16 UTC
```

Show running time for any running instances

---

site/index.html.md.erb

Put link to ruby sha at the top of the front page

---

events.yaml

Missed adding this in #361 apparently

Add events.yaml from old events.json and add a few recent events

---

Gemfile
Gemfile.lock
site/_framework/render.rb

Makes local development considerably faster and less frustrating.

Listen for file changes and auto-rebuild

---

continuous_reporting/gh_tasks/run_benchmarks.sh

Missed this one during the cleanup

Remove usage of removed arg

---

continuous_reporting/generate_and_upload_reports.rb

when we do the timeline reports

Only analyze and notify about regressions once

---

Gemfile
Gemfile.lock
continuous_reporting/gh_tasks/commit_benchmark_data.sh
continuous_reporting/gh_tasks/report_and_upload.sh
continuous_reporting/gh_tasks/run_benchmarks.sh

- **Install gems that are moving out of the stdlib**
- **Call bundle install to prepare for bundler 4**
- **Run under bundle exec to ensure we are using what we just installed**

Update gems and bundler usage

---

events.yaml

This logs the event of the gem updates in https://github.com/Shopify/yjit-bench/pull/371.

Add an event about gem updates

---

.github/workflows/scheduled_benchmarking.yml
basic_benchmark.rb
infrastructure/lib/yjit_benchmarking.rb
lib/yjit_metrics.rb
lib/yjit_metrics/defaults.rb
metrics-harness/harness.rb
rubies.yaml

- **Add ruby build configs for zjit prod and stats**
- **Collect zjit stats in result data**
- **Increase the allowed running time for benchmarks**
- **Include zjit builds by default**

Collect ZJIT metrics

---

basic_benchmark.rb
continuous_reporting/slack_build_notifier.rb
lib/metrics_app.rb
lib/metrics_app/repo_management.rb
lib/yjit_metrics/notifier.rb
test/slack_notification_test.rb

Improve slack notifications for failed commands
