lib/yjit-metrics.rb, lib/yjit-metrics/report_templates/blog_timeline_d3_template.html.erb, timeline_report.rb
This allows a JS-based "timeline deep dive" to show non-default data series and dynamically rescale the graph properly, but still shows the same thing on the front-page static view.
=> Add invisible data series to timeline graph

continuous_reporting/benchmark_and_update.rb
This PR adds command-line parameters to re-run old performance tripwire checks; to run without filing GitHub issues; and to run (and optionally file an issue) for a particular timestamp. It also loosens the absolute-magnitude worst drop that has to happen in order to file an issue, and documents everything better.
=> Better tooling around performance tripwires

.gitignore, continuous_reporting/generate_and_upload_reports.rb, lib/yjit-metrics.rb
From my googling uname -p isn't portable and just returns `arm` on mac. But unmame -m works. I also added some small changes to the error messages after I didn't understand them.
=> Makes build work on mac m1.

.gitmodules, lib/yjit-metrics/report_types/bloggable_speed_report.rb
This is part of https://github.com/Shopify/yjit-bench/pull/142#issuecomment-1337170356:
> if we agree on a way to store the info in yjit-bench going forward, I can work on PRs for yjit-bench and yjit-metrics to move the info to the right place.
I want us to start using [yjit-bench/benchmarks.yml](https://github.com/Shopify/yjit-bench/blob/main/benchmarks.yml) in yjit-bench to avoid maintaining the same metadata in two places. I don't care whether we use git submodules or not. I'm open to anything @noahgibbs prefers for doing so :)
=> Migrate metadata to yjit-bench/benchmarks.yml

README.md, basic_benchmark.rb, continuous_reporting/create_json_params_file.rb, lib/yjit-metrics/report_templates/blog_speed_details.html.erb
It hasn't been used in a long time.
=> Remove references to the yjit-extra-benchmarks repo

continuous_reporting/jenkins/Jenkinsfile_full_benchmark_run
closes #223
The last group of "full run" jobs have taken an average of 9 hours and 8 minutes.
Since the cron triggers the job to run 11 (and 13) hours later, it seems like we don't expect this job to take more than 12.
Putting the timeout on the "full run" job instead of the configurable one should mean that if anyone wanted to run the configurable one that one won't timeout (which means the job will be allowed to run longer but that also means it could block the regular ones). 
We won't know if this timeout actually achieves what we want until it happens again 🤷
=> Set a timeout on the full_benchmark_run Jenkins job

basic_benchmark.rb, test/basic_benchmark_script_test.rb, test/fake-yjit-bench/benchmarks/cycle_error/benchmark.rb, test/fake-yjit-bench/benchmarks/pass.rb
Setup fake benchmarks inside the test suite so we can add an integration test for the main script to make it faster to test changes.
If you've ever run the `./basic_benchmark.rb` script locally the test should work.
The fake benchmarks assume ../yjit-bench is present.
It also currently works regardless of what ruby configs you actually have built because there is currently no check on the `chruby` call in the script templates.
=> Create test to exercise the benchmark script and verify output

test/data/2021-09-13-100043_basic_benchmark_prod_ruby_no_jit.json, test/data/2021-09-13-100043_basic_benchmark_prod_ruby_with_yjit.json, test/data/2021-09-13-100043_basic_benchmark_ruby_30_with_mjit.json, test/data/2021-09-13-100043_basic_benchmark_yjit_stats.json
This env var was renamed to `BENCHMARK_CI_GITHUB_TOKEN` in e1fcd564c23469fd0c05da9b9fa967afcdb119fc and subsequently removed in 44f895bc03f0af32324187aeaefb473c6dd68073.
If we remove the remnants of it from the repo
then we won't have someone else find it and wonder if there is still action needed to rotate it.
The only remaining references are reading it (we don't currently set it anywhere)
and currently that remaining usage has been turned off:
https://github.com/Shopify/yjit-metrics/blob/1aa73367825042271f03d243b5fbea455b2220b0/continuous_reporting/benchmark_and_update.rb#L115-L118
https://github.com/Shopify/yjit-metrics/blob/1aa73367825042271f03d243b5fbea455b2220b0/continuous_reporting/gh_tasks/run_benchmarks.sh#L9
=> Remove noah's github token from test data files

continuous_reporting/jenkins/Jenkinsfile_configurable_run
Concurrently executed steps will operate in different workspace directories.
=> Remove results dir from each jenkins workspace

continuous_reporting/benchmark_and_update.rb
The arm server has been using a config generated about 10 months ago
and been taking 9 hours to run.
If I remove the file it takes 4 hours.
If I use the latest generated file it takes over 11.
As long as the arm server isn't getting updates and we don't really
want it to run for 2 or 3 times as long,
let's also disable it for x86 to see what difference it makes.
=> Disable variable warmup

basic_benchmark.rb
It can be used from the git dir without being installed.
The currently installed version is way too old.
=> Ensure ruby-build is cloned

lib/yjit-metrics/bench-results.rb, lib/yjit-metrics/report_types/bloggable_speed_report.rb
This way the version is accurate next year, and also if we regenerate old reports.
This implementation uses a placeholder to specify where we want the version (which means labels have to opt in)... We could just append it to all if we want, for example `No JIT 3.4.0dev`.
before
after
=> Get ruby version for graph label from metadata

lib/yjit-metrics/bench-results.rb, lib/yjit-metrics/report_templates/memory_timeline_d3_template.html.erb, lib/yjit-metrics/report_types/bloggable_speed_report.rb, lib/yjit-metrics/report_types/variable_warmup_report.rb, lib/yjit-metrics/report_types/yjit_stats_reports.rb, test/reporting_test.rb
This fixes up places in the code that search for short strings like `"no_jit"` to look for more specific strings like `"prod_ruby_no_jit"` so that we can add other configs that have consistent substrings like `"prev_ruby_no_jit"` without having that code find two matches and then raise errors (#258).
Also fix some bugs add more actual version lookups.
- **Fix config selection for single platform**
- **Clarify what config we skip and why in the memory timeline**
- **Search for full config names to avoid future conflicts**
- **Fix stats config lookup to actually match config name**
- **Put actual version into more of the "human" names**
- **Change "No JIT" to "CRuby"**
- **Add a few comments**
- **Remove commented test for report that was removed long ago**
- **Remove some unused …
=> Make config name substring searches use more specific names

basic_benchmark.rb, lib/yjit-metrics/bench-results.rb, lib/yjit-metrics/report_templates/blog_speed_details.html.erb, lib/yjit-metrics/report_types/bloggable_speed_report.rb, lib/yjit-metrics/report_types/variable_warmup_report.rb
This gets us the data for benchmarking against CRuby 3.3 with no JIT.
Then we can adjust https://github.com/Shopify/yjit-metrics/pull/257 to use this config as the baseline.
=> Benchmark against CRuby 3.3 to use as a baseline

continuous_reporting/generate_and_upload_reports.rb, lib/yjit-metrics/report_types/bloggable_speed_report.rb, site/_framework/render.rb, site/_layouts/benchmark_details.erb, site/autocopy.yml, site/index.html.md.erb
- **Make speedup SVG generation code more generic to enable future reuse**
- **Remove unnecessary attr_reader**
- **Remove unused method override and instance variable**
- **Prepare SpeedDetails (single and multi) report classes for subclassing**
- **Produce memory based graphs like we have for speed**
- **Skip stddev bars when the stddev is zero**
- **Include memory graphs after the speed graphs**
I intend to refactor the classes out to their own files and abstract methods, etc, but I had already done a bunch of renames and I'd like to keep the refactor separate from any feature changes.
I added the corresponding memory graph below each place where we showed the speed graphs
Currently the description is below the graph but I think it might be better above
I'm also thinking about maybe …
=> memory svg

continuous_reporting/gh_tasks/generate_bench_params.sh
The jenkins job runs
continuous_reporting/gh_tasks/git_update_yjit_metrics_repo.sh
right before this one which checks out the requested branch.
Don't undo that here.
https://github.com/Shopify/yjit-metrics/blob/9fe8ad5da6b8f2250c04be6b6d0b7da46473bb25/continuous_reporting/jenkins/Jenkinsfile_configurable_run#L117-L122
=> Respect YJIT_METRICS_VERSION param when generating json params

basic_benchmark.rb, basic_report.rb, lib/yjit_metrics/result_set.rb, timeline_report.rb
- **Show offending filename in "full_run" warnings**
- **Ignore keys about load and time in the full_run warning**
- **Move load and time measurements from "full_run" to "extra"**
This removes several thousand lines of output from the jenkins log.
=> Fix full_run warnings

continuous_reporting/jenkins/Jenkinsfile_full_benchmark_run
We're not doing anything with the data.
=> Disable automatic TruffleRuby benchmarking

site/_layouts/benchmark_details.erb, site/index.html.md.erb
- **Get platform from querystring when present**
- **Replace the querystring when switching platforms**
- **Use querystring for platform links on front page**
- **Add links to benchmark graph headers to make sharing links easier**
- **Add title for benchmark details pages**
When hovering the heading the ¶ shows and can be clicked:
closes #272
=> Use querystring for platform so that anchors can be used normally

site/_sass/jekyll-theme-slate.scss
On the details page, the "¶" was clipped if you zoomed in.
Before:
[before-em.webm](https://github.com/user-attachments/assets/acf45c9e-c103-4c5f-a8ed-1e46b03c9833)
After:
[after-em.webm](https://github.com/user-attachments/assets/acc7d133-f508-450a-8ea4-20acf8df92de)
=> Fix heading link getting clipped when zoomed

basic_benchmark.rb, continuous_reporting/benchmark_and_update.rb, continuous_reporting/generate_and_upload_reports.rb, lib/yjit_metrics/reports/speed_details_report.rb, lib/yjit_metrics/timeline_reports/yjit_speedup_timeline_report.rb, site/_framework/render.rb
- **Remove unnecessary entries from the overall items in the stats report**
- **Ignore the exe in the built site**
- **Add a few comments**
- **Skip the ln call when no files match**
- **Don't use gsub when you're only doing one substitution**
- **fixup! Add some comments**
- **Simplify dir glob to_a each**
- **Remove some unused functions**
=> Little cleanups

lib/yjit_metrics/timeline_reports/yjit_speedup_timeline_report.rb, timeline_report.rb
- **Do not include x86 stats in aarch64 timeline**
- **Skip overall for a timestamp if there is no stats config**
- **Remove duplicates from alltime data**
This gets rid of the weird diagonal line (that went from the end back to the beginning to start drawing over).
This also makes a lot more timestamps available:
Before
After
=> Fix the "all time" data for the stats timeline

continuous_reporting/slack_build_notifier.rb, test/slack_notification_test.rb
It's less likely to leak if it isn't directly in the env.
=> Find slack token in a file if configured

.github/workflows/scheduled_benchmarking.yml, .github/workflows/scheduled_reporting.yml, .github/workflows/wrapper.yml, continuous_reporting/create_json_params_file.rb
- **Validate format of timestamp arg**
- **Only use --cruby-name if non-empty**
- **Allow scheduled workflows to be triggered by UI**
- **Accept ruby commit and timestamp parameters when starting benchmarks**
=> Enable button in GitHub Actions

metrics-harness/harness.rb
Bumping from 10 to 30 added 5m to two yjit builds and 20m to the stats.
Assuming this will be similar and add another 30 minutes to the overall duration.
=> Increase YJIT warmup count to 50

lib/yjit_metrics/report.rb, lib/yjit_metrics/report_templates/blog_memory_details.html.erb, lib/yjit_metrics/report_templates/blog_speed_details.html.erb, lib/yjit_metrics/report_templates/blog_yjit_stats.html.erb, lib/yjit_metrics/report_templates/iteration_count.html.erb, lib/yjit_metrics/reports/blog_yjit_stats_report.rb, lib/yjit_metrics/reports/bloggable_single_report.rb, lib/yjit_metrics/reports/iteration_count_report.rb, lib/yjit_metrics/reports/memory_details_report.rb, lib/yjit_metrics/reports/speed_details_report.rb, site/_layouts/benchmark_details.erb, site/assets/css/style.css.scss
- **Make left-most column in table sticky and scroll horizontally**
This stops the table from overflowing the page and becoming unreadable
on mobile / smaller screens.
- **Move table below platform selector**
- **Deduplicate bench name to anchor tag logic and apply to 4th table**
The iterations report was the only one not doing it.
- **Stop forcing graph width**
This makes them fit in the window on mobile
and be slightly larger than they used to be on desktop.
- **Put radio in label to avoid a line break between radio and text**
- **Don't force fieldset to be two lines on mobile**
- **Move more styles from html to css**
Horizontal table scroll so it doesn't overflow the screen:
Style changes to graphs and platform selector so that it also doesn't overflow the viewport:
Compared to the …
=> Make site more responsive (and more usable on mobile)

continuous_reporting/generate_and_upload_reports.rb
This simplifies re-running any given timestamp/commit
(which is now easy to do via GitHub Actions).
=> Regenerate relevant reports when data files are more recent

lib/yjit_metrics/repo_management.rb
We already call git clean prior to this.
The make clean is removing needed files due to a change in CRuby:
https://github.com/ruby/ruby/pull/12212/files#r1874543682
=> Stop calling make clean after configuring

continuous_reporting/benchmark_and_update.rb, continuous_reporting/generate_and_upload_reports.rb, continuous_reporting/gh_tasks/run_benchmarks.sh, lib/yjit_metrics/reports/memory_details_report.rb, lib/yjit_metrics/reports/speed_details_report.rb, timeline_report.rb
- **Remove old, unused perf tripwire code**
- **Remove unused var**
- **Remove more unused code**
- **Remove unnecessary nearly duplicate regexp**
=> Remove unused code (mostly around perf tripwires)

Gemfile, Gemfile.lock, continuous_reporting/benchmark_and_update.rb, continuous_reporting/on_demand/dispatch.sh, continuous_reporting/slack_build_notifier.rb, lib/yjit_metrics/notifier.rb, test/slack_notification_test.rb
- **Update bundler**
- **Install logger for slack-ruby-client**
- **Move pidfile management into main method**
- **Don't error on removing files that don't exist**
- **Allow combining files with stdin for slack body**
- **Make slack notifications available to ruby processes**
- **Add error formatter to slack notifier**
- **Send slack notification directly from benchmarks script**
=> Send slack notification directly from benchmarks script

.github/workflows/test.yml, Gemfile, Gemfile.lock, lib/yjit_metrics.rb, lib/yjit_metrics/report.rb, lib/yjit_metrics/reports/per_bench_ruby_comparison_report.rb, test/benchmark_mocked_test.rb, test/reporting_test.rb
- **Upgrade minitest to fix dep on mutex_m**
- **Skip over warnings when looking for error output**
- **Use parens to remove warning**
- **Fix class names for test that must never have worked**
- **Use unfrozen string for buffer**
- **Run tests on CI**
=> Fix up tests and run them on CI

bin/analysis, continuous_reporting/generate_and_upload_reports.rb, continuous_reporting/slack_build_notifier.rb, lib/yjit_metrics.rb, lib/yjit_metrics/analysis.rb, site/_framework/render.rb, site/analysis.txt.erb, test/analysis_test.rb
This sets up regression detection for the `ratio_in_yjit` metric using the idea of
> Over the last 30-60 days, what was the lowest value? If we get a new value that’s 0.5 * stddev below the “floor” twice in a row, flag it?
I included the data that goes into the analysis to help us fine tune the algorithm and to make it easier to decide if a notification is worth investigating.
This is more or less what the slack notification would like:
refs #366
=> Implement initial regression detection

basic_benchmark.rb
The new shipit benchmark seems to be the first one to actually leave this behind.
=> Use rmtree to remove bootsnap cache dir

continuous_reporting/on_demand/launch.sh, infrastructure/terraform/ec2.tf, infrastructure/terraform/yjit-metrics-init-script.sh
- **Explicitly load the env file created by the user script when launching jobs**
- **Make user-data env available for both bash and zsh**
- **Comment on where you can find the generated user data init script**
=> Ensure instance user-data is available to scripts regardless of default shell

continuous_reporting/gh_tasks/report_and_upload.sh
Make sure we have up to date metadata about the benchmarks.
=> Update yjit-bench before doing reporting

infrastructure/lib/yjit_benchmarking.rb
missed this in #416 
tested at https://github.com/Shopify/yjit-metrics/actions/runs/16684422612/job/47230467214#step:5:144
=> Ensure benchmark command uses yjit-metrics-name from params

basic_benchmark.rb, lib/yjit_metrics.rb, lib/yjit_metrics/repo_management.rb, metrics-harness/run_harness.sh.erb, test/benchmark_mocked_test.rb
`make install` in the ruby repo is failing with:
> /usr/local/ruby/lib/ruby/gems/3.4.0/gems/bundler-2.6.2/lib/bundler/runtime.rb:319:in 'Bundler::Runtime#check_for_activated_spec!': You have already activated stringio 3.1.2, but your Gemfile requires stringio 3.1.7. Since stringio is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports stringio as a default gem. (Gem::LoadError)
=> Don't let unrelated commands inherit our bundler env

site/_layouts/basic.erb, site/_layouts/benchmark_details.erb, site/_layouts/default.erb, site/_layouts/timeline.erb
Now that `yjit-bench` has been renamed to `ruby-bench` and we're going to let `speed.ruby-lang.org` point to the website, it's probably nice to start calling it "Ruby Benchmarks".
There would be more things we want to change for `speed.ruby-lang.org`, but I'm thinking this is a good enough start.
=> Change "YJIT Benchmarks" to "Ruby Benchmarks"

site/CNAME
This PR updates `sites/CNAME` so that the benchmark server will not revert `rubybench/yjit-reports/CNAME` to `speed.yjit.org`, which expires the custom domain settings.
=> Update CNAME to speed.ruby-lang.org

basic_benchmark.rb, lib/yjit_metrics/defaults.rb
Don't use "with" as that is an historical artifact of the yjit graphs.
=> Spell zjit build config consistently
